language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install pytest-cov
script: 
  - python -m pytest --cov=./ --cov-config .coveragerc #apps #--doctest-modules
after_success:
- codecov
